import '../styles/globals.css'
import Head from 'next/head'
import Script from 'next/script'
import SuportButton from '../components/SuportButton'


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>rfood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex flex-col items-center justify-center min-h-screen p-20"
      >
        <Component {...pageProps} />
      </div>
    </>
  )
}


export default MyApp
