import '../styles/globals.css'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="
        bg-gradient-to-r from-purple-500 to-purple-900
        min-h-screen
        min-w-screen
        "
      >
        <Component {...pageProps} />
      </div>
    </>
  )
}

export default MyApp
