//Next / React 
import Head from 'next/head'
import styles from '../styles/Home.module.css'

//Chakra Grid components
import { Box } from '@chakra-ui/react'
import { Center, Square, Circle } from '@chakra-ui/react'
import { Stack, HStack, VStack } from '@chakra-ui/react'
import { Wrap, WrapItem } from '@chakra-ui/react'

//Chakra UI components
import { Button, ButtonGroup } from '@chakra-ui/react'
import { Skeleton, SkeletonCircle, SkeletonText } from '@chakra-ui/react'
import { Image } from '@chakra-ui/react'
import {
    List,
    ListItem,
    ListIcon,
    OrderedList,
    UnorderedList,
} from '@chakra-ui/react'
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'
import { useToast } from '@chakra-ui/react'


//Chakra UI Typography components
import { Heading } from '@chakra-ui/react'
import { Text } from '@chakra-ui/react'

//Components
import RandomMeal from '../components/random-meal'


function Refresh() {
  window.location.reload(false);
}


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack direction={'column'} spacing={100}>
        <Center paddingTop={100}>
            <Heading as="h1" size="xl">
              🍔 Random Meal
              </Heading>
          </Center>
          <Center>
            <Box>
              <Button onClick={Refresh}>
                🍔 Get more random foods
              </Button>
            </Box>
          </Center>
          <Center>
            <Box paddingTop={200}>
              <Heading>Scrooll down</Heading>
            </Box>
        </Center>
      </Stack>
      
      <Box paddingBottom={100} paddingTop={200}>
        <Stack spacing={8} direction={'row'}>
          <Box overflowX={'-moz-initial'}>
            <RandomMeal />
          </Box>
          <Box overflowX={'-moz-initial'}>
            <RandomMeal />
          </Box>
          <Box overflowX={'-moz-initial'}>
            <RandomMeal />
          </Box>
        </Stack>
      </Box>
    </div>
  )
}
